# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: React Card Component CI

on:
  create:
    tags:
      - 0.0.1* # Push events to v1 tag
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Build on Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - id: npm_ci
        run: npm ci
      - run: npm run test
      - run: npm run rollup
  npm-publish:
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org/'
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  storybook-publish:
    needs: npm-publish
    steps:
      - uses: actions/checkout@v2
      - uses: fregante/setup-git-token@v1
        with:
          name: joon610
          email: joon610@gmail.com
          token: ${{ secrets.TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm ci
      - name: build Storybook
        run: npm run build-storybook
      - name: Git Connect Storybook repo
        working-directory: ./storybook-static
        run: |
          git init
          git remote add origin https://github.com/joon610/react-card-storybook
          git checkout -b main
          git add .
          git commit -m 'Storybook publish from workflow'
      - name: story book publish
        working-directory: ./storybook-static
        run: |
          git push origin main -f
